#!/usr/bin/env python

import sys

from treedecode import decodeTreeFile

tree	=	open(sys.argv[1],'rb').read()
tree	=	decodeTreeFile ( tree )
with open(sys.argv[2], 'wb') as outputFile:
	outputFile.write ( tree )


