#!/usr/bin/env python

import sys

from treeencode import encodeTreeFile

tree	=	open(sys.argv[1],'rb').read()
tree	=	encodeTreeFile ( tree )
with open(sys.argv[2], 'wb') as outputFile:
	outputFile.write ( tree )

