#!/bin/bash


BUNDLE="${1}"
REPO="${2}"
BRANCH_NAME="${3}"

[ -z "${BUNDLE}" ] && echo "Usage: tdimbue <bundlePath> <repoPath> <newBranchName>" && exit 1
[ -z "${REPO}" ] && echo "Usage: tdimbue <bundlePath> <repoPath> <newBranchName>" && exit 1
[ -z "${BRANCH_NAME}" ] && echo "Usage: tdimbue <bundlePath> <repoPath> <newBranchName>" && exit 1


pushd "${BUNDLE}" > /dev/null
	BUNDLE="$(pwd)"
popd > /dev/null


cd "${REPO}"


git branch "${BRANCH_NAME}"
git checkout "${BRANCH_NAME}"



# Add all the blobs

echo "Imbuing blobs..."

TYPE=blob
for i in "${BUNDLE}/${TYPE}".*
do
	SHA1_c="$(echo """${i}""" | sed """s/.*${TYPE}.//""")"
	SHA1_r="$(git hash-object -t ${TYPE} """${i}""")"
	[[ "${SHA1_c}" != "${SHA1_r}" ]] && echo "Error hashing ${i} (${SHA1_c} vs ${SHA1_r}); exiting" && exit 1
	git hash-object -w -t ${TYPE} "${i}" > /dev/null
done



# Add all the commits

echo "Imbuing commits..."

TYPE=commit
for i in "${BUNDLE}/${TYPE}".*
do
	SHA1_c="$(echo """${i}""" | sed """s/.*${TYPE}.//""")"
	SHA1_r="$(git hash-object -t ${TYPE} """${i}""")"
	[[ "${SHA1_c}" != "${SHA1_r}" ]] && echo "Error hashing ${i} (${SHA1_c} vs ${SHA1_r}); exiting" && exit 1
	git hash-object -w -t ${TYPE} "${i}" > /dev/null
done




# Add all the trees

echo "Imbuing trees..."

TMP="/tmp/$(uuidgen)"

TYPE=tree
for i in "${BUNDLE}/${TYPE}".*
do
	treeencode "${i}" > ${TMP}
	SHA1_c="$(echo """${i}""" | sed """s/.*${TYPE}.//""")"
	SHA1_r="$(git hash-object -t ${TYPE} """${TMP}""")"
	[[ "${SHA1_c}" != "${SHA1_r}" ]] && echo "Error hashing ${i} (${SHA1_c} vs ${SHA1_r}); exiting" && exit 1
	git hash-object -w -t ${TYPE} "${TMP}" > /dev/null
	rm "${TMP}"
done




# Update the head

git update-ref HEAD "$(cat """${BUNDLE}/HEAD""")"
git checkout HEAD
echo "Note: if 'git status' reports changes, you may have to run 'git reset --hard'" # don't automatically do this, because that's poor form

